module.exports = {
  arrowParens: 'avoid',
  bracketSameLine: false,
  bracketSpacing: false,
  embeddedLanguageFormatting: 'off',
  endOfLine: 'lf',
  jsxSingleQuote: false,
  printWidth: 90,
  quoteProps: 'as-needed',
  semi: false,
  singleAttributePerLine: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
}
